unit NewService_Impl;

{----------------------------------------------------------------------------}
{ This unit was automatically generated by the RemObjects SDK after reading  }
{ the RODL file associated with this project .                               }
{                                                                            }
{ This is where you are supposed to code the implementation of your objects. }
{----------------------------------------------------------------------------}

{$I RemObjects.inc}

interface

uses
  {vcl:} Classes, SysUtils, 
  {RemObjects:} uROXMLIntf, uROClientIntf, uROTypes, uROServer, uROServerIntf, uROSessions,
  {Generated:} NewLibrary_Intf;

type
  { TNewService }
  TNewService = class(TRORemotable, INewService)
  private
  protected
    { INewService methods }
    function Sum(const A: Integer; const B: Integer): Integer;
    function GetServerTime: DateTime;
    function HelloWorld: UnicodeString;
  end;

implementation

uses
  {Generated:} NewLibrary_Invk, uROClassFactories;

procedure Create_NewService(out anInstance : IUnknown);
begin
  anInstance := TNewService.Create;
end;

{ NewService }
function TNewService.Sum(const A: Integer; const B: Integer): Integer;
begin
end;

function TNewService.GetServerTime: DateTime;
begin
end;

function TNewService.HelloWorld: UnicodeString;
begin
  Result := 'Hello World!';
end;

var
  fClassFactory: IROClassFactory;
initialization
  //fClassFactory := TROClassFactory.Create('NewService', {$IFDEF FPC}@{$ENDIF}Create_NewService, TNewService_Invoker);
  // RegisterForZeroConf(fClassFactory,'_NewService_rosdk._tcp.');
  fClassFactory := TROPooledClassFactory.Create('NewService', Create_NewService, TNewService_Invoker, 50);

finalization
  UnRegisterClassFactory(fClassFactory);
  fClassFactory := nil;

end.
